backend:
  name: github
  repo: Papaya-Voldemort/Wiki # Make sure this matches your GitHub repo
  branch: main

media_folder: "public/images" # Folder for uploaded images
public_folder: "/images" # Path for images in the published site

collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/pages
    label: "Pages" # Used in the UI
    folder: "content/pages" # The path to the folder where your pages are stored
    create: true # Allow users to create new pages
    slug: "{{slug}}" # Filename template
    fields: [
      { label: "Title", name: "title", widget: "string" },
      { label: "Body", name: "body", widget: "markdown" },
    ]
